HomeTask2
BayMaxMB/budget-tracker pull request #3
Opened 2022-03-17 18:57 UTC by BayMaxMB

I need suggestion on how to include routes/auth into server.js in a best way, I needed to include passport lib inside this auth.js fie

2022-03-17 19:05 UTC, BayMaxMB commented
And please suggest me better option to generate unique integer number user ID

How to be 100% sure that ID generator cannot generate same ID after some time? Checking the whole database before assigning?

2022-03-18 06:00 UTC, Lokki17 requested changes
Fix remarks and merge

2022-03-18 06:00 UTC, Lokki17 commented on database.js
> +const users = [{
Move data to another file

2022-03-18 06:00 UTC, Lokki17 commented on routes/auth.js
> +router.post('/register', (req, res) => {
Move router hanlders (functions) to separate file

2022-03-18 06:01 UTC, Lokki17 commented
> And please suggest me better option to generate unique integer number user ID
> 
> How to be 100% sure that ID generator cannot generate same ID after some time? Checking the whole database before assigning?

https://stackoverflow.com/questions/23327010/how-to-generate-unique-id-with-node-js

2022-03-18 06:02 UTC, Lokki17 commented
> I need suggestion on how to include routes/auth into server.js in a best way, I needed to include passport lib inside this auth.js fie

I didn't get you

2022-03-19 20:46 UTC, merged